"""status column for all courses

Revision ID: 9bbbfbf33969
Revises: 18f7d8adad06
Create Date: 2025-03-24 00:16:43.852470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bbbfbf33969'
down_revision = '18f7d8adad06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.SmallInteger(), nullable=False))

    with op.batch_alter_table('user_course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.SmallInteger(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_course', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
