"""change name for user course, now custom course

Revision ID: e2d2a29561ca
Revises: 9bbbfbf33969
Create Date: 2025-03-24 00:35:35.964266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2d2a29561ca'
down_revision = '9bbbfbf33969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('progress', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('user_ref_id', sa.Integer(), nullable=False),
    sa.Column('course_ref_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_ref_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_ref_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custom_course', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_course_course_ref_id'), ['course_ref_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_course_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_course_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_course_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_course_user_ref_id'), ['user_ref_id'], unique=False)

    with op.batch_alter_table('user_course', schema=None) as batch_op:
        batch_op.drop_index('ix_user_course_course_ref_id')
        batch_op.drop_index('ix_user_course_description')
        batch_op.drop_index('ix_user_course_name')
        batch_op.drop_index('ix_user_course_timestamp')
        batch_op.drop_index('ix_user_course_user_ref_id')

    op.drop_table('user_course')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_course',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('progress', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('user_ref_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_ref_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_ref_id'], ['course.id'], name='user_course_course_ref_id_fkey'),
    sa.ForeignKeyConstraint(['user_ref_id'], ['user.id'], name='user_course_user_ref_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_course_pkey')
    )
    with op.batch_alter_table('user_course', schema=None) as batch_op:
        batch_op.create_index('ix_user_course_user_ref_id', ['user_ref_id'], unique=False)
        batch_op.create_index('ix_user_course_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_user_course_name', ['name'], unique=False)
        batch_op.create_index('ix_user_course_description', ['description'], unique=False)
        batch_op.create_index('ix_user_course_course_ref_id', ['course_ref_id'], unique=False)

    with op.batch_alter_table('custom_course', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_course_user_ref_id'))
        batch_op.drop_index(batch_op.f('ix_custom_course_timestamp'))
        batch_op.drop_index(batch_op.f('ix_custom_course_name'))
        batch_op.drop_index(batch_op.f('ix_custom_course_description'))
        batch_op.drop_index(batch_op.f('ix_custom_course_course_ref_id'))

    op.drop_table('custom_course')
    # ### end Alembic commands ###
